### ISSUE TITLE
Shiny: Parallel or Single Threaded

### ISSUE THREAD

**Issue by 0ldM4j0r** [PoonLab/KaphiShiny#13]
During today's dev meeting we discussed that while the tsv file is being generated, plots should be created. These two operations running in parallel, but I am not sure whether or not the first operation (generating the tsv) should be run in parallel within itself. As of now, generating the tsv in the shiny app isn't being run in parallel since the machines I am testing on (Nagisa, Mac Mini, My laptop) don't have the same number of threads.

**Comment by ArtPoon** [comment]
Shiny is single-threaded by design - add an argument to the run SMC function that will generate plots from TSV outputs.
