### ISSUE TITLE
Refactor app.R into settings, ui and server scripts

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/KaphiShiny#15]

**Comment by ArtPoon** [comment]
After discussing with @0ldM4j0r , it looks like the two-file approach will not run within RStudio.  Instead, let's peel out the data into a separate file, and modularize within the `app.R` file.

**Comment by 0ldM4j0r** [comment]
I have made a new branch called "refactor" on which I will be refactoring the code for KaphiShiny

**Comment by 0ldM4j0r** [comment]
I finished refactoring the code on the branch `refactor` 0d6b65ec7bd0668182ca3cbb7338799872f716b8. I merged `refactor` into `master` ae1ecb6d9ba43e5dffa50afe20e8c676cd9f6049.
