### ISSUE TITLE
Plotting mean trajectory and posterior approximation graphs during tsv generation

### ISSUE THREAD

**Issue by 0ldM4j0r** [PoonLab/KaphiShiny#18]
As of commit 984ab67ef22f73de00e350a8c1c9e6655144db5b mean trajectory graphs are generated after tsv generation. However, as stated in issue #17 an error occurs when trying to generate posterior approximation graphs. After fixing issue #17 mean trajectory and posterior approximation graphs should be plotted during tsv generation.

**Comment by gtng92** [comment]
Note: there updating plot renderings has a delay of 3-4 're-renders'. So if I tell the plot to update every 10 iterations, the user will only see the first plot at Step 30 or 40. If I tell it to update every 5 iterations, the first plot will usually render after step 15. Currently updating the plots every 5 iterations.
