### ISSUE TITLE
Compartmental models running too long

### ISSUE THREAD

**Issue by 0ldM4j0r** [PoonLab/KaphiShiny#22]
In ~27 hours KaphiShiny has finished 13 iterations. A normal run in R goes for about 120 - 170 iterations.

**Comment by gtng92** [comment]
@0ldM4j0r and I decided to attempt running with multi-threads for yule model. We used 10 threads and it worked! 1000 particles in 258.9 seconds. Attempting multi-threads for compartmental model now.

**Comment by 0ldM4j0r** [comment]
It works for compartmental, I have 3 steps done with 100 particles in 901.7s, I will leave it running until it finishes. I will post updates here.

**Comment by ArtPoon** [comment]
👍

**Comment by 0ldM4j0r** [comment]
I left the 100 particle compartmental run over the weekend to run, it has reached 2175 steps and epsilon isn't changing.

**Comment by 0ldM4j0r** [comment]
I was using the tree generated by the yule model that could be the problem. I will rerun with a tree generated by the compartmental model.

Also I believe that this issue is related to PoonLab/Kaphi#124.

**Comment by 0ldM4j0r** [comment]
100 particle compartmental model using a tree generated from the compartmental model successfully finished in 1836.2 s. I will run it again with 1000 particle to establish a time benchmark.

**Comment by 0ldM4j0r** [comment]
1000 particle compartmental model using a tree generated from the compartmental model successfully finished in 15636.1 s. 

I will open a new issue and will run it with 1000 particles on the tree generated from the yule model. (see issue  #23)
